server:
  port: 8000

spring:
  profiles:
    active:
    list: prod, dev, local

  application:
    name: member-service
  datasource:
    url: jdbc:postgresql://localhost:5432/member_database
    username: sanho1tech
    password: sanho0601
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
#          show_sql: true
#          format_sql: true
      generate-ddl: true
      show-sql: true
  sql:
    init:
      mode: always

  redis:
    #    host: hitup-redis.go5u2n.clustercfg.apn2.cache.amazonaws.com  # elastiCache
    host: 127.0.0.1
    port: 6379


cloud:
  aws:
    credentials:
      accessKey: AKIAJ5O2JI2FW5ZZX6XA
      secretKey: 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
    s3:
      bucket: hitup
      url: hitup.s3.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloud-front:
      domain-name: d3bdkrhj3pjg86.cloudfront.net
      distributionId: E1GAAS0DQFYG0Z

security:
  basic:
    server_id: albanote_id_blac
    server_pwd: albanote_pwd_2013
  member:
    password: 123123

token:
  expiration_time: 86400000
  secret: alba_note_user_token
refresh_token:
  expiration_time: 6220800000
  secret: alba_note_user_refresh_token

